/**
 * Portable AI resource initializer.
 *
 * Creates tool-neutral prompts and Anthropic-style skills under agent-resources/.
 * These resources are designed to be shared by VS Code Copilot now and OpenCode later.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { ensureDir, exists } from '../utils/fs-utils';

export interface PortableResourceInitResult {
  createdDirectories: string[];
  createdFiles: string[];
}

const PORTABLE_RESOURCE_DIRECTORIES: string[] = [
    ".product-dev/prompts",
    ".product-dev/prompts/commands",
    ".product-dev/prompts/output-schemas",
    ".product-dev/prompts/system",
    "agent-resources",
    "agent-resources/prompts/commands",
    "agent-resources/prompts/output-schemas",
    "agent-resources/prompts/system",
    "agent-resources/skills",
    "agent-resources/skills/bank-data-engineering",
    "agent-resources/skills/bank-data-engineering/evals",
    "agent-resources/skills/bank-data-engineering/references",
    "agent-resources/skills/frontend-review",
    "agent-resources/skills/frontend-review/evals",
    "agent-resources/skills/nl2sql",
    "agent-resources/skills/nl2sql/evals",
    "agent-resources/skills/nl2sql/references",
    "agent-resources/skills/prompt-quality",
    "agent-resources/skills/prompt-quality/evals",
    "agent-resources/skills/python-engineering",
    "agent-resources/skills/python-engineering/evals",
    "agent-resources/skills/skill-creator",
    "agent-resources/skills/skill-creator/evals",
    "agent-resources/skills/skill-creator/references",
    "agent-resources/skills/springboot-engineering",
    "agent-resources/skills/springboot-engineering/evals",
    "agent-resources/skills/sql-engineering",
    "agent-resources/skills/sql-engineering/evals",
    "agent-resources/skills/sql-engineering/references",
    "agent-resources/skills/sql-review",
    "agent-resources/skills/sql-review/evals",
    "agent-resources/skills/sql-review/references",
    "agent-resources/skills/sql-translate",
    "agent-resources/skills/sql-translate/evals",
    "agent-resources/skills/sql-translate/references",
    "agent-resources/skills/design-md",
    "agent-resources/skills/design-md/references",
    "agent-resources/skills/design-md/examples",
    "agent-resources/skills/design-md/evals",
    "agent-resources/skills/diagramming",
    "agent-resources/skills/diagramming/references",
    "agent-resources/skills/diagramming/examples",
    "agent-resources/skills/diagramming/evals"
];

const PORTABLE_RESOURCE_FILES: Record<string, string> = {
    ".product-dev/prompts/README.md": "# Project Prompt Overrides\n\nUse this directory for project-specific prompt overrides. These files are loaded before extension built-in prompt defaults and are designed to be portable to OpenCode.\n",
    ".product-dev/prompts/commands/nl2sql.md": "# NL2SQL Command Prompt\n\nConvert natural language business questions into safe SQL.\n\nSupported dialects: PostgreSQL, Oracle, BigQuery, MaxCompute/ODPS, MySQL, SQL Server, Snowflake, Databricks/Spark SQL, Hive.\n\nRequired output: business question, dialect, assumptions, required schema context, metric/dimension/grain definition, SQL, join/filter explanation, validation SQL, DQ/reconciliation checks, performance notes, privacy/access risks, open questions, next command.\n",
    ".product-dev/prompts/commands/sql-review.md": "# SQL Review Prompt\n\nReview SQL for correctness, safety, performance, governance, and production readiness.\n\nAlways check dialect, business logic, driving table, join cardinality, grain mismatch, duplicate amplification, null handling, SCD2/temporal joins, soft delete filters, partition pruning, amount/count reconciliation, SQL injection risk, sensitive data exposure, DQ, validation SQL, and rollback/recovery notes.\n",
    ".product-dev/prompts/commands/sql-translate.md": "# SQL Dialect Translation Prompt\n\nTranslate SQL between PostgreSQL, Oracle, BigQuery, MaxCompute/ODPS, MySQL, SQL Server, Snowflake, Databricks/Spark SQL, and Hive while preserving business semantics.\n\nAlways review data types, date/time functions, string functions, null semantics, window functions, CTEs, MERGE/UPSERT, temporary tables, sequences/identity columns, partition syntax, quoting, arrays/structs, UDFs, and unsupported functions.\n",
    ".product-dev/prompts/output-schemas/nl2sql.md": "# NL2SQL Output\n\n## 1. Business Question\n## 2. Dialect and Assumptions\n## 3. Required Schema Context\n## 4. Metric / Dimension / Grain Definition\n## 5. Generated SQL\n## 6. Join and Filter Explanation\n## 7. Validation SQL\n## 8. DQ / Reconciliation Checks\n## 9. Performance Notes\n## 10. Privacy / Access Risks\n## 11. Open Questions\n## 12. Next Command\n",
    ".product-dev/prompts/output-schemas/sql-review.md": "# SQL Review Report\n\n## 1. Review Summary\n## 2. Dialect and Execution Context\n## 3. Correctness Findings\n## 4. Join / Grain / Aggregation Findings\n## 5. Performance Findings\n## 6. Data Quality / Reconciliation Findings\n## 7. Security / Privacy Findings\n## 8. Maintainability Findings\n## 9. Required Fixes\n## 10. Rewritten SQL if Needed\n## 11. Validation SQL\n## 12. Decision\n## 13. Next Command\n",
    ".product-dev/prompts/output-schemas/sql-translate.md": "# SQL Translation Output\n\n## 1. Source Dialect\n## 2. Target Dialect\n## 3. Translation Summary\n## 4. Translated SQL\n## 5. Semantic Preservation Notes\n## 6. Function / Type Mapping Table\n## 7. Unsupported or Risky Constructs\n## 8. Performance and Partition Notes\n## 9. Validation SQL\n## 10. Migration Checklist\n## 11. Next Command\n",
    ".product-dev/prompts/system/base.md": "# Portable System Prompt\n\nYou are an enterprise product engineering and data engineering assistant. Follow local policy packs first, then project prompt overrides, then portable skills.\n\nFor SQL/data work, always include assumptions, dialect, data grain, join safety, DQ, reconciliation, lineage, privacy, performance, validation SQL, and rollback notes where applicable.\n",
    "agent-resources/README.md": "# Portable Agent Resources\n\nThis directory is the tool-neutral source of truth for prompts, output schemas, and skills. It is intentionally separate from VS Code extension source code so the same assets can be reused by Copilot, OpenCode, Claude Code, Codex, or another AI IDE.\n\n## Precedence\n\n1. `.product-dev/policy-packs/`\n2. `.product-dev/prompts/`\n3. `.product-dev/skills/`\n4. `agent-resources/`\n5. extension built-in defaults\n\n## OpenCode migration\n\nUse `AGENTS.md`, `.opencode/commands/*.md`, and `.opencode/agents/*.md` as shims that point to this folder instead of duplicating prompts.\n",
    "agent-resources/prompts/commands/nl2sql.md": "# NL2SQL Command Prompt\n\nConvert natural language business questions into safe SQL.\n\nSupported dialects: PostgreSQL, Oracle, BigQuery, MaxCompute/ODPS, MySQL, SQL Server, Snowflake, Databricks/Spark SQL, Hive.\n\nRequired output: business question, dialect, assumptions, required schema context, metric/dimension/grain definition, SQL, join/filter explanation, validation SQL, DQ/reconciliation checks, performance notes, privacy/access risks, open questions, next command.\n",
    "agent-resources/prompts/commands/sql-review.md": "# SQL Review Prompt\n\nReview SQL for correctness, safety, performance, governance, and production readiness.\n\nAlways check dialect, business logic, driving table, join cardinality, grain mismatch, duplicate amplification, null handling, SCD2/temporal joins, soft delete filters, partition pruning, amount/count reconciliation, SQL injection risk, sensitive data exposure, DQ, validation SQL, and rollback/recovery notes.\n",
    "agent-resources/prompts/commands/sql-translate.md": "# SQL Dialect Translation Prompt\n\nTranslate SQL between PostgreSQL, Oracle, BigQuery, MaxCompute/ODPS, MySQL, SQL Server, Snowflake, Databricks/Spark SQL, and Hive while preserving business semantics.\n\nAlways review data types, date/time functions, string functions, null semantics, window functions, CTEs, MERGE/UPSERT, temporary tables, sequences/identity columns, partition syntax, quoting, arrays/structs, UDFs, and unsupported functions.\n",
    "agent-resources/prompts/output-schemas/nl2sql.md": "# NL2SQL Output\n\n## 1. Business Question\n## 2. Dialect and Assumptions\n## 3. Required Schema Context\n## 4. Metric / Dimension / Grain Definition\n## 5. Generated SQL\n## 6. Join and Filter Explanation\n## 7. Validation SQL\n## 8. DQ / Reconciliation Checks\n## 9. Performance Notes\n## 10. Privacy / Access Risks\n## 11. Open Questions\n## 12. Next Command\n",
    "agent-resources/prompts/output-schemas/sql-review.md": "# SQL Review Report\n\n## 1. Review Summary\n## 2. Dialect and Execution Context\n## 3. Correctness Findings\n## 4. Join / Grain / Aggregation Findings\n## 5. Performance Findings\n## 6. Data Quality / Reconciliation Findings\n## 7. Security / Privacy Findings\n## 8. Maintainability Findings\n## 9. Required Fixes\n## 10. Rewritten SQL if Needed\n## 11. Validation SQL\n## 12. Decision\n## 13. Next Command\n",
    "agent-resources/prompts/output-schemas/sql-translate.md": "# SQL Translation Output\n\n## 1. Source Dialect\n## 2. Target Dialect\n## 3. Translation Summary\n## 4. Translated SQL\n## 5. Semantic Preservation Notes\n## 6. Function / Type Mapping Table\n## 7. Unsupported or Risky Constructs\n## 8. Performance and Partition Notes\n## 9. Validation SQL\n## 10. Migration Checklist\n## 11. Next Command\n",
    "agent-resources/prompts/system/base.md": "# Portable System Prompt\n\nYou are an enterprise product engineering and data engineering assistant. Follow local policy packs first, then project prompt overrides, then portable skills.\n\nFor SQL/data work, always include assumptions, dialect, data grain, join safety, DQ, reconciliation, lineage, privacy, performance, validation SQL, and rollback notes where applicable.\n",
    "agent-resources/skills/README.md": "# @product-dev Skills\n\nSkills follow the portable Agent Skills pattern:\n\n```text\n<skill-name>/\n├── SKILL.md\n├── references/\n├── scripts/\n├── examples/\n└── evals/\n```\n\n`SKILL.md` must contain `name` and `description` frontmatter. The description is the primary discovery/trigger signal. Keep `SKILL.md` concise and move long standards, dialect matrices, examples, and rubrics to `references/`.\n\nRun:\n\n```text\n@product-dev /skill-scan\n@product-dev /skill-review\n@product-dev /skill-run sql-review review this SQL\n```\n",
    "agent-resources/skills/bank-data-engineering/SKILL.md": "---\nname: bank-data-engineering\ndescription: Use this skill for bank-grade data engineering tasks including data contracts, STTM, DQ rules, reconciliation, lineage, scheduler design, privacy controls, production runbooks, cost controls, and data-review workflows. Trigger whenever the task mentions banking data, source-to-target mapping, DQ, reconciliation, audit, lineage, SLA, batch jobs, sensitive fields, regulatory controls, or production data release.\nappliesTo: data,sql,dbschema,pipeline,datacontract,sttm,dq,reconcile,lineage,migration,scheduler,privacy,data-test,data-review,catalog,semantic,cost,runbook\ntriggers: data,sql,dq,sttm,reconcile,lineage,数据,对账,血缘,质量,银行,审计\n---\n\n# Bank Data Engineering\n\n## Use this skill when\n\nThe task is about enterprise or banking data development, especially where traceability, audit evidence, privacy, SLA, reconciliation, and production operability matter.\n\n## Workflow\n\n1. Establish business purpose, owner, SLA, data grain, source systems, target consumers, and environment.\n2. Check the data contract before designing SQL or pipelines.\n3. Produce STTM before transformation implementation.\n4. Design DQ, reconciliation, lineage, privacy, scheduler, and runbook together; they are not afterthoughts.\n5. Flag missing policy pack files when thresholds, severity, retention, or privacy classification are company-specific.\n\n## Deep reference\n\nRead `references/bank-data-checklist.md` for the full control checklist.\n\n## Output pattern\n\nReturn sections for data contract, STTM, SQL/pipeline design, DQ, reconciliation, lineage, privacy, scheduler, data tests, release gates, runbook, risks, and next command.\n",
    "agent-resources/skills/bank-data-engineering/evals/evals.json": "{\n  \"skill_name\": \"bank-data-engineering\",\n  \"evals\": [\n    {\n      \"id\": 1,\n      \"prompt\": \"Use the bank-data-engineering skill on a realistic enterprise task with incomplete context and produce targeted questions plus a draft artifact.\",\n      \"expected_output\": \"Clear assumptions, missing questions, structured output, and next command.\",\n      \"files\": []\n    },\n    {\n      \"id\": 2,\n      \"prompt\": \"Review an existing artifact using bank-data-engineering and identify Blocker/High/Medium/Low findings.\",\n      \"expected_output\": \"Severity-based findings with evidence, impact, fix, and validation step.\",\n      \"files\": []\n    }\n  ]\n}\n",
    "agent-resources/skills/bank-data-engineering/references/bank-data-checklist.md": "# Bank Data Engineering Checklist\n\n## Data contract\n\nOwner, SLA, grain, primary/unique keys, nullable fields, enum rules, partition strategy, sensitive classification, compatibility, downstream consumers.\n\n## STTM\n\nSource field, target field, type conversion, transformation rule, filter, join rule, default/null handling, DQ check, reconciliation check, owner.\n\n## Controls\n\nDQ, reconciliation, field lineage, privacy/masking, scheduler, backfill, release gate, runbook, incident escalation.\n",
    "agent-resources/skills/frontend-review/SKILL.md": "---\nname: frontend-review\ndescription: Use this skill for frontend product engineering and review tasks involving React, Vue, Angular, page flows, route design, components, state management, API hooks, forms, loading/error/empty states, accessibility, telemetry, performance, and frontend tests. Trigger when the user asks for UI implementation, frontend review, journey analysis, or product experience improvements.\nappliesTo: frontend,journey,review,test\ntriggers: react,vue,angular,frontend,ui,页面,组件\n---\n\n# Frontend Review\n\nCheck page purpose, route behavior, component boundaries, state ownership, API hooks, form validation, loading/empty/error/permission states, accessibility, responsive behavior, performance, telemetry, unit tests, component tests, and E2E tests. Tie findings back to product journey and user friction.\n",
    "agent-resources/skills/frontend-review/evals/evals.json": "{\n  \"skill_name\": \"frontend-review\",\n  \"evals\": [\n    {\n      \"id\": 1,\n      \"prompt\": \"Use the frontend-review skill on a realistic enterprise task with incomplete context and produce targeted questions plus a draft artifact.\",\n      \"expected_output\": \"Clear assumptions, missing questions, structured output, and next command.\",\n      \"files\": []\n    },\n    {\n      \"id\": 2,\n      \"prompt\": \"Review an existing artifact using frontend-review and identify Blocker/High/Medium/Low findings.\",\n      \"expected_output\": \"Severity-based findings with evidence, impact, fix, and validation step.\",\n      \"files\": []\n    }\n  ]\n}\n",
    "agent-resources/skills/nl2sql/SKILL.md": "---\nname: nl2sql\ndescription: Convert natural language business questions into schema-grounded SQL with ambiguity handling, metric/grain definition, safe joins, validation queries, and dialect-specific syntax. Use this skill whenever the user asks in natural language for a query, report, metric, dashboard dataset, ad-hoc analysis, or SQL generation for PostgreSQL, Oracle, BigQuery, MaxCompute/ODPS, MySQL, SQL Server, Snowflake, Databricks/Spark SQL, or Hive.\nappliesTo: nl2sql,sql,semantic,catalog\ntriggers: natural language to sql,nl2sql,自然语言,生成sql,查询,报表,指标\n---\n\n# NL2SQL\n\n## Use this skill when\n\nThe user describes a data question in business language and needs SQL.\n\n## Workflow\n\n1. Restate the business question and identify metric, dimension, filter, date range, and output grain.\n2. Ground the SQL in known schema. If table/column names are unknown, ask targeted questions and optionally provide a labeled draft skeleton.\n3. Select dialect and use dialect-specific date, string, null, array/struct, and partition syntax.\n4. Explain joins, filters, aggregations, privacy implications, and assumptions.\n5. Provide validation SQL and at least one DQ/reconciliation check.\n\n## Reference\n\nRead `references/schema-grounding.md` when schema is incomplete or ambiguous.\n\n## Output pattern\n\nBusiness question → dialect → assumptions → required schema → SQL → explanation → validation SQL → DQ/reconciliation → risks → next command.\n",
    "agent-resources/skills/nl2sql/evals/evals.json": "{\n  \"skill_name\": \"nl2sql\",\n  \"evals\": [\n    {\n      \"id\": 1,\n      \"prompt\": \"Use the nl2sql skill on a realistic enterprise task with incomplete context and produce targeted questions plus a draft artifact.\",\n      \"expected_output\": \"Clear assumptions, missing questions, structured output, and next command.\",\n      \"files\": []\n    },\n    {\n      \"id\": 2,\n      \"prompt\": \"Review an existing artifact using nl2sql and identify Blocker/High/Medium/Low findings.\",\n      \"expected_output\": \"Severity-based findings with evidence, impact, fix, and validation step.\",\n      \"files\": []\n    }\n  ]\n}\n",
    "agent-resources/skills/nl2sql/references/schema-grounding.md": "# Schema Grounding for NL2SQL\n\nAsk for or infer explicitly:\n\n- Table names and business meanings\n- Column names, types, and sensitive classifications\n- Primary/unique keys\n- Partition columns\n- Date/time fields\n- Metric definitions\n- Join relationships\n- SCD2 validity fields\n- Soft-delete/status fields\n\nIf missing, produce a draft SQL skeleton with placeholders and a list of required metadata questions.\n",
    "agent-resources/skills/prompt-quality/SKILL.md": "---\nname: prompt-quality\ndescription: Use this skill whenever a user gives a rough, vague, overloaded, or mixed-language request and the system needs to turn it into a precise execution prompt with role, goal, context, constraints, output schema, missing questions, assumptions, and next action. Also use it before product, frontend, backend, data, SQL, review, summary, rewrite, and loop commands to normalize user intent.\nappliesTo: *\ntriggers: prompt,优化,需求,设计,review,总结,压缩\n---\n\n# Prompt Quality\n\n## Use this skill when\n\nThe user input is incomplete, ambiguous, too broad, or needs to be converted into an execution-ready prompt for Copilot, OpenCode, Claude Code, Codex, or an internal agent workflow.\n\n## Workflow\n\n1. Extract the user's real objective before rewriting wording.\n2. Preserve hard constraints exactly, especially technology stack, database dialect, policy pack, environment, and output format.\n3. Split the request into role, task, context, constraints, output schema, quality bar, and next command.\n4. Ask only targeted questions when missing information blocks safe execution. Otherwise proceed with clearly labeled assumptions.\n5. End with one concrete next step.\n\n## Output pattern\n\nReturn optimized prompt, assumptions, missing context questions, suggested skills/policies to load, expected output artifacts, and next command.\n\n## Safety boundary\n\nDo not invent company policy, table schemas, credentials, production thresholds, or regulatory rules. Refer users to Policy Pack files for mandatory rules.\n",
    "agent-resources/skills/prompt-quality/evals/evals.json": "{\n  \"skill_name\": \"prompt-quality\",\n  \"evals\": [\n    {\n      \"id\": 1,\n      \"prompt\": \"Use the prompt-quality skill on a realistic enterprise task with incomplete context and produce targeted questions plus a draft artifact.\",\n      \"expected_output\": \"Clear assumptions, missing questions, structured output, and next command.\",\n      \"files\": []\n    },\n    {\n      \"id\": 2,\n      \"prompt\": \"Review an existing artifact using prompt-quality and identify Blocker/High/Medium/Low findings.\",\n      \"expected_output\": \"Severity-based findings with evidence, impact, fix, and validation step.\",\n      \"files\": []\n    }\n  ]\n}\n",
    "agent-resources/skills/python-engineering/SKILL.md": "---\nname: python-engineering\ndescription: Use this skill for Python backend and data service design or review, including FastAPI, Flask, Pydantic, SQLAlchemy, Alembic, pytest, typed Python, async jobs, data access, packaging, observability, and production runtime commands.\nappliesTo: backend,python,api,review,test\ntriggers: python,fastapi,flask,pydantic,pytest\n---\n\n# Python Backend Engineering\n\nUse typed Python, Pydantic schemas, route/service/repository separation, explicit database sessions, migrations, structured logging, exception handling, pytest, lint/type checks, packaging, environment configuration, and runtime commands. Do not generate Java files for Python-only tasks.\n",
    "agent-resources/skills/python-engineering/evals/evals.json": "{\n  \"skill_name\": \"python-engineering\",\n  \"evals\": [\n    {\n      \"id\": 1,\n      \"prompt\": \"Use the python-engineering skill on a realistic enterprise task with incomplete context and produce targeted questions plus a draft artifact.\",\n      \"expected_output\": \"Clear assumptions, missing questions, structured output, and next command.\",\n      \"files\": []\n    },\n    {\n      \"id\": 2,\n      \"prompt\": \"Review an existing artifact using python-engineering and identify Blocker/High/Medium/Low findings.\",\n      \"expected_output\": \"Severity-based findings with evidence, impact, fix, and validation step.\",\n      \"files\": []\n    }\n  ]\n}\n",
    "agent-resources/skills/skill-creator/SKILL.md": "---\nname: skill-creator\ndescription: Create, review, refactor, and improve Agent Skills in Anthropic-style SKILL.md format. Use whenever the user wants to create a new skill, improve existing skills, optimize skill descriptions for triggering, add references/scripts/evals, convert prompts into reusable skills, or assess whether a skill is too broad, unsafe, overfit, or hard to migrate to OpenCode.\nappliesTo: skill-init,skill-scan,skill-run,skill-review,prompt\ntriggers: skill,SKILL.md,技能,提示词能力,agent skill,opencode skill,claude skill\n---\n\n# Skill Creator\n\n## Use this skill when\n\nThe task involves creating, improving, testing, packaging, or reviewing a reusable skill.\n\n## Skill anatomy\n\nA good skill directory should look like this:\n\n```text\nskill-name/\n├── SKILL.md\n├── references/\n├── scripts/\n├── examples/\n└── evals/\n```\n\n## Creation workflow\n\n1. Capture intent: what the skill enables, when it should trigger, expected outputs, constraints, and risks.\n2. Draft a concise `SKILL.md`: put triggering information in `description`, not buried in the body.\n3. Move long or rarely needed details into `references/` and point to them from `SKILL.md`.\n4. Add 2-3 realistic eval prompts with expected behavior.\n5. Review for security: no hidden network calls, credential handling, exfiltration, or surprising side effects.\n6. Run the skill on eval prompts, compare outputs, then revise.\n\n## Quality rubric\n\nRead `references/quality-rubric.md` when doing a detailed review.\n\n## Output pattern\n\nReturn skill purpose, trigger cases, proposed directory tree, complete `SKILL.md`, recommended references/evals/scripts, risk notes, and next test command.\n",
    "agent-resources/skills/skill-creator/evals/evals.json": "{\n  \"skill_name\": \"skill-creator\",\n  \"evals\": [\n    {\n      \"id\": 1,\n      \"prompt\": \"Use the skill-creator skill on a realistic enterprise task with incomplete context and produce targeted questions plus a draft artifact.\",\n      \"expected_output\": \"Clear assumptions, missing questions, structured output, and next command.\",\n      \"files\": []\n    },\n    {\n      \"id\": 2,\n      \"prompt\": \"Review an existing artifact using skill-creator and identify Blocker/High/Medium/Low findings.\",\n      \"expected_output\": \"Severity-based findings with evidence, impact, fix, and validation step.\",\n      \"files\": []\n    }\n  ]\n}\n",
    "agent-resources/skills/skill-creator/references/quality-rubric.md": "# Skill Quality Rubric\n\n## Required\n\n- Frontmatter has `name` and `description`.\n- Description states when to use the skill and includes realistic trigger contexts.\n- Body explains workflow, output behavior, safety boundaries, and references.\n\n## Good\n\n- `SKILL.md` is concise and below 500 lines.\n- Long details live in `references/`.\n- Deterministic helpers live in `scripts/` and are documented.\n- `evals/evals.json` has realistic prompts and expected behavior.\n\n## Bad smells\n\n- Description is only a noun phrase.\n- Skill duplicates mandatory policy rules instead of referencing policy packs.\n- Instructions are too broad or conflict with other skills.\n- Skill contains hidden network behavior, secrets, or surprising side effects.\n",
    "agent-resources/skills/springboot-engineering/SKILL.md": "---\nname: springboot-engineering\ndescription: Use this skill for Java Spring Boot backend design and review, including controller/DTO/service/repository layering, validation, transaction boundaries, security, audit logging, OpenAPI contracts, integration tests, error handling, idempotency, and production configuration.\nappliesTo: backend,springboot,api,review,test\ntriggers: java,spring,springboot,jvm\n---\n\n# Spring Boot Engineering\n\nUse layered architecture: Controller, DTO, validation, Service, Repository, Entity, Mapper, Exception, Config, Test. Check transaction boundaries, idempotency, security annotations, audit logging, OpenAPI alignment, integration tests, and environment profiles. Do not generate Python files for Java-only tasks.\n",
    "agent-resources/skills/springboot-engineering/evals/evals.json": "{\n  \"skill_name\": \"springboot-engineering\",\n  \"evals\": [\n    {\n      \"id\": 1,\n      \"prompt\": \"Use the springboot-engineering skill on a realistic enterprise task with incomplete context and produce targeted questions plus a draft artifact.\",\n      \"expected_output\": \"Clear assumptions, missing questions, structured output, and next command.\",\n      \"files\": []\n    },\n    {\n      \"id\": 2,\n      \"prompt\": \"Review an existing artifact using springboot-engineering and identify Blocker/High/Medium/Low findings.\",\n      \"expected_output\": \"Severity-based findings with evidence, impact, fix, and validation step.\",\n      \"files\": []\n    }\n  ]\n}\n",
    "agent-resources/skills/sql-engineering/SKILL.md": "---\nname: sql-engineering\ndescription: Use this skill for production SQL generation, optimization, review, dialect-specific design, query safety, DQ validation, reconciliation SQL, lineage extraction, and SQL migration across PostgreSQL, Oracle, BigQuery, MaxCompute/ODPS, MySQL, SQL Server, Snowflake, Databricks/Spark SQL, and Hive. Trigger whenever the user asks for SQL, query optimization, SQL review, join rules, dialect conversion, natural language to SQL, partition pruning, cost optimization, or production data validation.\nappliesTo: sql,nl2sql,sql-translate,sql-review,dq,reconcile,lineage,data-review,cost\ntriggers: sql,nl2sql,postgresql,oracle,bigquery,maxcompute,odps,hive,snowflake,databricks,review,translate,转换,优化\n---\n\n# SQL Engineering\n\n## Use this skill when\n\nThe task needs SQL that is correct, performant, auditable, and safe to run in enterprise data environments.\n\n## Workflow\n\n1. Identify dialect, business grain, driving table, date window, and expected output.\n2. Verify schema grounding. If metadata is missing, ask for it or label the SQL as a draft skeleton.\n3. Check join cardinality before aggregation. Explain one-to-one, one-to-many, or many-to-many risk.\n4. Add partition pruning and cost controls for BigQuery, MaxCompute, Snowflake, Databricks, and Hive-like engines.\n5. Add validation SQL, DQ SQL, and reconciliation SQL where the output could affect reporting, risk, finance, or customer data.\n\n## References\n\n- Read `references/dialect-matrix.md` when translating or using dialect-specific functions.\n- Read `references/join-safety.md` when joins, SCD2, soft deletes, or aggregation are involved.\n\n## Output pattern\n\nAlways include dialect, assumptions, generated/revised SQL, explanation, validation SQL, performance notes, DQ/reconciliation checks, privacy risks, and next command.\n",
    "agent-resources/skills/sql-engineering/evals/evals.json": "{\n  \"skill_name\": \"sql-engineering\",\n  \"evals\": [\n    {\n      \"id\": 1,\n      \"prompt\": \"Use the sql-engineering skill on a realistic enterprise task with incomplete context and produce targeted questions plus a draft artifact.\",\n      \"expected_output\": \"Clear assumptions, missing questions, structured output, and next command.\",\n      \"files\": []\n    },\n    {\n      \"id\": 2,\n      \"prompt\": \"Review an existing artifact using sql-engineering and identify Blocker/High/Medium/Low findings.\",\n      \"expected_output\": \"Severity-based findings with evidence, impact, fix, and validation step.\",\n      \"files\": []\n    }\n  ]\n}\n",
    "agent-resources/skills/sql-engineering/references/dialect-matrix.md": "# SQL Dialect Matrix\n\n| Area | PostgreSQL | Oracle | BigQuery | MaxCompute/ODPS | Snowflake | Databricks/Spark SQL | Hive |\n|---|---|---|---|---|---|---|---|\n| Date diff | date - date / AGE | MONTHS_BETWEEN, TRUNC | DATE_DIFF | DATEDIFF | DATEDIFF | datediff | datediff |\n| Current date | CURRENT_DATE | SYSDATE / CURRENT_DATE | CURRENT_DATE() | GETDATE() / CURRENT_DATE | CURRENT_DATE | current_date() | current_date |\n| Null handling | COALESCE | NVL/COALESCE | IFNULL/COALESCE | NVL/COALESCE | COALESCE | coalesce | coalesce |\n| Limit | LIMIT | FETCH FIRST / ROWNUM | LIMIT | LIMIT | LIMIT | LIMIT | LIMIT |\n| Merge | INSERT ON CONFLICT / MERGE newer versions | MERGE | MERGE | MERGE INTO support varies by table type | MERGE | MERGE | limited |\n\nAlways verify exact engine/version behavior before production use.\n",
    "agent-resources/skills/sql-engineering/references/join-safety.md": "# Join Safety Reference\n\n1. Declare the driving table and output grain.\n2. For every join, state cardinality: 1:1, 1:N, N:1, or N:M.\n3. Do not aggregate money/count metrics after a one-to-many join without deduplication strategy.\n4. SCD2 joins require effective_start/effective_end conditions.\n5. Soft-delete/status fields require filters.\n6. Partitioned tables require date/partition predicates.\n7. Produce validation SQL: row count before/after join, duplicate key check, null join key check, and amount/count reconciliation.\n",
    "agent-resources/skills/sql-review/SKILL.md": "---\nname: sql-review\ndescription: Review SQL for production readiness, correctness, business semantics, join safety, performance, cost, data quality, reconciliation, lineage, privacy, and dialect-specific risks. Use this skill whenever the user asks to review, check, optimize, approve, migrate, or troubleshoot SQL for PostgreSQL, Oracle, BigQuery, MaxCompute/ODPS, MySQL, SQL Server, Snowflake, Databricks/Spark SQL, or Hive.\nappliesTo: sql-review,sql,data-review,review\ntriggers: sql review,review sql,检查sql,sql评审,性能优化,join,partition,cost\n---\n\n# SQL Review\n\n## Use this skill when\n\nThe user provides SQL or asks whether SQL is safe, correct, performant, or production-ready.\n\n## Review workflow\n\n1. Identify dialect, intent, grain, driving table, and output consumers.\n2. Check correctness: filters, joins, nulls, date windows, SCD2, soft deletes, duplicate amplification, and aggregation grain.\n3. Check performance/cost: partition pruning, clustering/index usage, scan size, shuffle/sort pressure, and unnecessary CTE/materialization.\n4. Check data controls: DQ, reconciliation, lineage, privacy, masking, and audit evidence.\n5. Return severity-based findings with evidence, impact, fix, and validation SQL.\n\n## Reference\n\nRead `references/review-rubric.md` for the full checklist.\n\n## Output pattern\n\nUse Blocker / High / Medium / Low. Every finding must include evidence, impact, fix, and validation SQL or verification step.\n",
    "agent-resources/skills/sql-review/evals/evals.json": "{\n  \"skill_name\": \"sql-review\",\n  \"evals\": [\n    {\n      \"id\": 1,\n      \"prompt\": \"Use the sql-review skill on a realistic enterprise task with incomplete context and produce targeted questions plus a draft artifact.\",\n      \"expected_output\": \"Clear assumptions, missing questions, structured output, and next command.\",\n      \"files\": []\n    },\n    {\n      \"id\": 2,\n      \"prompt\": \"Review an existing artifact using sql-review and identify Blocker/High/Medium/Low findings.\",\n      \"expected_output\": \"Severity-based findings with evidence, impact, fix, and validation step.\",\n      \"files\": []\n    }\n  ]\n}\n",
    "agent-resources/skills/sql-review/references/join-safety.md": "# Join Safety Reference\n\n1. Declare the driving table and output grain.\n2. For every join, state cardinality: 1:1, 1:N, N:1, or N:M.\n3. Do not aggregate money/count metrics after a one-to-many join without deduplication strategy.\n4. SCD2 joins require effective_start/effective_end conditions.\n5. Soft-delete/status fields require filters.\n6. Partitioned tables require date/partition predicates.\n7. Produce validation SQL: row count before/after join, duplicate key check, null join key check, and amount/count reconciliation.\n",
    "agent-resources/skills/sql-review/references/review-rubric.md": "# SQL Review Rubric\n\n## Blocker\n\nWrong grain, unsafe join amplification, missing critical date filter on large partitioned table, exposure of sensitive fields, SQL that cannot run in target dialect.\n\n## High\n\nMissing validation SQL, SCD2 join missing validity range, soft-delete filter missing, high-cost full scan, ambiguous metric definition.\n\n## Medium\n\nMaintainability issues, unclear aliases, repeated logic, missing comments for complex transformation.\n\n## Low\n\nFormatting, naming, minor simplification.\n\nEach finding should include evidence, impact, fix, and validation.\n",
    "agent-resources/skills/sql-translate/SKILL.md": "---\nname: sql-translate\ndescription: Translate SQL between PostgreSQL, Oracle, BigQuery, MaxCompute/ODPS, MySQL, SQL Server, Snowflake, Databricks/Spark SQL, and Hive while preserving business semantics. Use this skill when the user asks for SQL dialect conversion, migration, modernization, engine replacement, syntax compatibility, date/function mapping, MERGE/UPSERT translation, partition syntax changes, or cloud data warehouse migration.\nappliesTo: sql-translate,sql,migration,data-review\ntriggers: sql translate,方言转换,oracle,bigquery,maxcompute,postgresql,hive,snowflake,databricks,migration\n---\n\n# SQL Translate\n\n## Workflow\n\n1. Identify source and target dialect. If either is missing, ask before producing final SQL.\n2. Preserve business semantics before syntax style.\n3. Map data types, date/time functions, string functions, null semantics, CTEs, windows, MERGE/UPSERT, temp tables, sequences, partition filters, quoting, arrays/structs, and UDFs.\n4. Mark non-equivalent functions and required manual decisions.\n5. Provide translated SQL, compatibility notes, validation SQL, and performance/cost adjustments.\n\n## Reference\n\nRead `references/dialect-matrix.md` for mapping guidance.\n",
    "agent-resources/skills/sql-translate/evals/evals.json": "{\n  \"skill_name\": \"sql-translate\",\n  \"evals\": [\n    {\n      \"id\": 1,\n      \"prompt\": \"Use the sql-translate skill on a realistic enterprise task with incomplete context and produce targeted questions plus a draft artifact.\",\n      \"expected_output\": \"Clear assumptions, missing questions, structured output, and next command.\",\n      \"files\": []\n    },\n    {\n      \"id\": 2,\n      \"prompt\": \"Review an existing artifact using sql-translate and identify Blocker/High/Medium/Low findings.\",\n      \"expected_output\": \"Severity-based findings with evidence, impact, fix, and validation step.\",\n      \"files\": []\n    }\n  ]\n}\n",
    "agent-resources/skills/sql-translate/references/dialect-matrix.md": "# SQL Dialect Matrix\n\n| Area | PostgreSQL | Oracle | BigQuery | MaxCompute/ODPS | Snowflake | Databricks/Spark SQL | Hive |\n|---|---|---|---|---|---|---|---|\n| Date diff | date - date / AGE | MONTHS_BETWEEN, TRUNC | DATE_DIFF | DATEDIFF | DATEDIFF | datediff | datediff |\n| Current date | CURRENT_DATE | SYSDATE / CURRENT_DATE | CURRENT_DATE() | GETDATE() / CURRENT_DATE | CURRENT_DATE | current_date() | current_date |\n| Null handling | COALESCE | NVL/COALESCE | IFNULL/COALESCE | NVL/COALESCE | COALESCE | coalesce | coalesce |\n| Limit | LIMIT | FETCH FIRST / ROWNUM | LIMIT | LIMIT | LIMIT | LIMIT | LIMIT |\n| Merge | INSERT ON CONFLICT / MERGE newer versions | MERGE | MERGE | MERGE INTO support varies by table type | MERGE | MERGE | limited |\n\nAlways verify exact engine/version behavior before production use.\n",
    ".product-dev/prompts/commands/design-md.md": "# DESIGN.md Command Prompt\n\nGenerate a Stitch-compatible DESIGN.md from existing frontend source code or user design intent.\n\nRead repository evidence first: package.json, routes, pages, components, theme files, CSS variables, Tailwind config, design tokens, Storybook files, and existing docs.\n\nRequired structure: visual theme, color palette and roles, typography, component stylings, layout principles, depth/elevation, do/don't rules, responsive behavior, agent prompt guide, source evidence and assumptions, next command.\n",
    ".product-dev/prompts/output-schemas/design-md.md": "# DESIGN.md Output\n\n## 1. Visual Theme & Atmosphere\n## 2. Color Palette & Roles\n## 3. Typography Rules\n## 4. Component Stylings\n## 5. Layout Principles\n## 6. Depth & Elevation\n## 7. Do's and Don'ts\n## 8. Responsive Behavior\n## 9. Agent Prompt Guide\n## 10. Source Evidence and Assumptions\n## 11. Next Command\n",
    "agent-resources/prompts/commands/design-md.md": "# DESIGN.md Command Prompt\n\nGenerate a Stitch-compatible DESIGN.md from existing frontend source code or user design intent.\n\nThis file is tool-neutral and can be consumed by Copilot, OpenCode, Stitch-style workflows, Claude Code, or other coding agents.\n\nAlways separate repository-backed evidence from assumptions.\n",
    "agent-resources/prompts/output-schemas/design-md.md": "# DESIGN.md Output\n\n## 1. Visual Theme & Atmosphere\n## 2. Color Palette & Roles\n## 3. Typography Rules\n## 4. Component Stylings\n## 5. Layout Principles\n## 6. Depth & Elevation\n## 7. Do's and Don'ts\n## 8. Responsive Behavior\n## 9. Agent Prompt Guide\n## 10. Source Evidence and Assumptions\n## 11. Next Command\n",
    "agent-resources/prompts/commands/prd.md": "# PRD Command Prompt\n\nCreate or update a Product Requirements Document that is executable by engineers, QA, and autonomous coding agents.\n\n## Required behavior\n\n1. Ask only critical clarifying questions if needed; use lettered options.\n2. Define goals, non-goals, users, constraints, success metrics, dependencies, and risks.\n3. Produce small user stories suitable for Ralph-style one-iteration execution.\n4. Acceptance criteria must be concrete and verifiable.\n5. UI stories need visual verification criteria.\n6. Data stories need DQ/reconciliation criteria.\n7. Code stories need typecheck/lint/test criteria.\n8. End with whether `/story-split` or `/prd-json` should run next.\n",
    "agent-resources/prompts/commands/story-split.md": "# Story Split Command Prompt\n\nSplit PRD, feature design, or a broad request into Ralph-sized stories.\n\n## Rules\n\n- One story per fresh agent context.\n- Dependency order first, business value second.\n- Split too-large stories until each has a focused implementation boundary.\n- Each story has ID, title, type, description, acceptance criteria, dependency, and validation evidence.\n- Do not combine unrelated frontend, backend, data, and release work into one story.\n",
    "agent-resources/prompts/commands/prd-json.md": "# PRD JSON Command Prompt\n\nConvert PRD Markdown or feature design into Ralph-compatible `scripts/ralph/prd.json`.\n\n## Contract\n\nReturn a conversion summary and valid JSON with:\n\n- project\n- branchName: `ralph/<feature-name>`\n- description\n- userStories[] with id, title, description, acceptanceCriteria, priority, passes:false, notes:\"\"\n\n## Validation\n\nCheck JSON parseability, story size, dependency ordering, acceptance criteria quality, and quality evidence.\n",
    "agent-resources/prompts/commands/ralph-readiness.md": "# Ralph Readiness Command Prompt\n\nReview whether the project is ready for Ralph-style loop execution.\n\n## Check\n\n- PRD completeness\n- prd.json schema and story size\n- dependency ordering\n- acceptance criteria verifiability\n- quality commands available\n- progress.txt append-only memory\n- AGENTS.md / CLAUDE.md reusable pattern guidance\n- branchName and git readiness\n- stop condition and COMPLETE behavior\n\nReturn a readiness decision: Approved, Approved with Conditions, or Not Ready.\n",
    "agent-resources/prompts/output-schemas/story-split.md": "# Ralph Story Split Output Schema\n\n## 1. Source Scope Summary\n## 2. Dependency-ordered Story Table\n## 3. Split Decisions\n## 4. Validation Evidence\n## 5. Open Questions\n## 6. Next Command\n",
    "agent-resources/prompts/output-schemas/prd-json.md": "# Ralph prd.json Output Schema\n\n## 1. Conversion Summary\n## 2. Assumptions\n## 3. prd.json\n## 4. Validation Findings\n## 5. Next Command\n",
    "agent-resources/prompts/output-schemas/ralph-readiness.md": "# Ralph Readiness Output Schema\n\n## 1. Readiness Decision\n## 2. Blockers\n## 3. High Findings\n## 4. Medium / Low Findings\n## 5. Required Fixes\n## 6. Safe Next Command\n",
    "agent-resources/skills/prd-planning/SKILL.md": "---\nname: prd-planning\ndescription: Generate implementation-ready PRDs with Ralph-sized user stories, essential clarifying questions, explicit goals/non-goals, concrete acceptance criteria, and delivery-ready requirements. Use this skill when the user asks to create a PRD, plan a feature, write requirements, convert ideas into product scope, or prepare work for autonomous coding loops.\n---\n\n# PRD Planning Skill\n\n## When to use\n\nUse this skill for `/prd`, `/feature`, `/story-split`, `/task`, and any request that needs a requirements document suitable for developers, QA, and coding agents.\n\n## Workflow\n\n1. If the request is ambiguous, ask only 3-5 essential clarifying questions with lettered options so the user can answer quickly.\n2. Define the problem, goals, non-goals, target users, constraints, success metrics, and release boundaries.\n3. Convert requirements into small user stories that can be implemented and verified independently.\n4. For every story, write concrete acceptance criteria. Avoid vague language like \"works well\" or \"good UX\".\n5. Label story type: UI, backend, data, API, integration, test, release, or documentation.\n6. Add validation evidence: typecheck/lint/test for code, browser/manual visual verification for UI, DQ/reconciliation for data.\n\n## References\n\nRead `references/prd-quality-rubric.md` before producing the final PRD.\n\n## Output pattern\n\nPRD overview → goals/non-goals → users → user journey → user stories → functional requirements → NFRs → dependencies → acceptance criteria → Ralph readiness notes → risks → open questions → next command.\n",
    "agent-resources/skills/prd-planning/references/prd-quality-rubric.md": "# PRD Quality Rubric\n\n## Blocker issues\n\n- Missing problem statement or goal.\n- Requirements are not testable.\n- User stories are too large for one implementation session.\n- Dependencies are hidden or ordered incorrectly.\n- Acceptance criteria are vague.\n\n## Ralph story requirements\n\nEach story must include:\n\n- ID: US-001 style.\n- Title: short action-oriented name.\n- Type: UI/backend/data/API/test/release/documentation.\n- Description: As a [user/role], I want [capability] so that [benefit].\n- Acceptance criteria: concrete and checkable.\n- Priority: dependency order first, then business priority.\n- Dependencies: previous story IDs or external prerequisites.\n- Validation evidence: typecheck/lint/test, visual verification, DQ/reconciliation, or release evidence.\n\n## Splitting rule\n\nIf a story cannot be described in 2-3 sentences and verified independently, split it.\n",
    "agent-resources/skills/prd-planning/evals/evals.json": "{\n  \"skill_name\": \"prd-planning\",\n  \"evals\": [\n    {\n      \"id\": \"prd-001\",\n      \"prompt\": \"Create a PRD for a new dashboard with filters, export, API, and data quality checks.\",\n      \"expected_output\": \"Clarifying questions if needed, small stories, explicit non-goals, acceptance criteria, validation evidence, and next command.\"\n    }\n  ]\n}\n",
    "agent-resources/skills/ralph-prd/SKILL.md": "---\nname: ralph-prd\ndescription: Convert PRDs or feature specs into Ralph-compatible prd.json with dependency-ordered, one-iteration userStories, passes:false status, empty notes, strict acceptance criteria, and branchName ralph/<feature-name>. Use when the user asks for prd.json, Ralph format, story conversion, autonomous loop preparation, or PRD-to-agent task conversion.\n---\n\n# Ralph PRD Converter Skill\n\n## Job\n\nConvert a Markdown PRD, feature design, task list, or user request into a Ralph-compatible `scripts/ralph/prd.json`.\n\n## Output JSON contract\n\n```json\n{\n  \"project\": \"Project Name\",\n  \"branchName\": \"ralph/feature-name\",\n  \"description\": \"Short feature description\",\n  \"userStories\": [\n    {\n      \"id\": \"US-001\",\n      \"title\": \"Story title\",\n      \"description\": \"As a role, I want capability so that benefit.\",\n      \"acceptanceCriteria\": [\"Criterion 1\", \"Typecheck passes\"],\n      \"priority\": 1,\n      \"passes\": false,\n      \"notes\": \"\"\n    }\n  ]\n}\n```\n\n## Conversion rules\n\n1. One PRD user story becomes one JSON entry unless it is too large.\n2. Split large stories before JSON conversion.\n3. Order by dependencies: schema/data contract → backend/API → frontend/UI → integration → dashboard/report → tests/release.\n4. All stories start with `passes:false` and `notes:\"\"`.\n5. Every story includes verifiable acceptance criteria.\n6. Every story includes quality evidence: typecheck/lint/test, visual verification, DQ/reconciliation, or release evidence.\n7. Branch name is kebab-case and prefixed with `ralph/`.\n\n## References\n\nRead `references/story-sizing.md` and `references/prd-json-schema.md`.\n",
    "agent-resources/skills/ralph-prd/references/story-sizing.md": "# Ralph Story Sizing\n\n## Right-sized examples\n\n- Add one database column and migration.\n- Implement one API endpoint with tests.\n- Add one UI component to an existing page.\n- Add one filter dropdown and persist state.\n- Add one DQ rule and validation SQL.\n\n## Too large; split these\n\n- Build the entire dashboard.\n- Add authentication end-to-end.\n- Refactor the API layer.\n- Migrate all Oracle SQL to BigQuery.\n- Build all data quality controls.\n\n## Dependency ordering\n\n1. Schema/data contract.\n2. Data migration or backend model.\n3. API/service logic.\n4. UI component/page integration.\n5. Tests and release readiness.\n",
    "agent-resources/skills/ralph-prd/references/prd-json-schema.md": "# Ralph prd.json Schema\n\nRequired top-level fields:\n\n- project: string\n- branchName: string, must start with `ralph/`\n- description: string\n- userStories: array\n\nRequired userStories fields:\n\n- id: `US-001`, `US-002`, ...\n- title: string\n- description: string\n- acceptanceCriteria: string[]\n- priority: number, dependency order first\n- passes: false\n- notes: empty string\n\nValidation checks:\n\n- JSON must parse.\n- Story IDs must be unique and sequential.\n- Priority values must be unique and ascending.\n- No story may depend on a later story.\n- Acceptance criteria cannot contain only vague statements.\n",
    "agent-resources/skills/ralph-prd/evals/evals.json": "{\n  \"skill_name\": \"ralph-prd\",\n  \"evals\": [\n    {\n      \"id\": \"ralph-prd-001\",\n      \"prompt\": \"Convert a PRD with a dashboard, API, and database change into prd.json.\",\n      \"expected_output\": \"Valid JSON with split stories, dependency ordering, passes:false, notes empty, and validation criteria.\"\n    }\n  ]\n}\n",
    "agent-resources/skills/ralph-loop/SKILL.md": "---\nname: ralph-loop\ndescription: Prepare, run, and review Ralph-style autonomous coding loops where each iteration starts with clean context, reads prd.json and progress.txt, implements one passes:false story, runs quality checks, commits, updates progress, and stops when all stories pass. Use for /loop, /loop-next, /ralph-readiness, long-running coding workflows, and autonomous implementation planning.\n---\n\n# Ralph Loop Skill\n\n## Workflow\n\n1. Read `scripts/ralph/prd.json`.\n2. Read `scripts/ralph/progress.txt`, especially Codebase Patterns.\n3. Check branch from `branchName`.\n4. Pick the highest-priority story where `passes:false`.\n5. Implement exactly one story per iteration.\n6. Run project quality checks.\n7. Update AGENTS.md or CLAUDE.md only with reusable codebase learnings.\n8. Mark the story `passes:true` only if evidence passes.\n9. Append to progress.txt; never replace it.\n10. Stop with COMPLETE only when all stories pass.\n\n## Safety limits\n\n- Do not work on multiple stories in one iteration.\n- Do not commit broken code.\n- Do not mark `passes:true` without validation evidence.\n- Do not store long story-specific details in AGENTS.md.\n\n## References\n\nRead `references/progress-memory.md` and `references/quality-gates.md`.\n",
    "agent-resources/skills/ralph-loop/references/progress-memory.md": "# Ralph Memory Files\n\n## prd.json\n\nSource of truth for story state. `passes:false` means pending. `passes:true` means completed with evidence.\n\n## progress.txt\n\nAppend-only iteration log. Must preserve:\n\n- story ID\n- what changed\n- files changed\n- quality checks run\n- reusable learnings\n- blockers and follow-up notes\n\n## AGENTS.md / CLAUDE.md\n\nOnly add reusable patterns, gotchas, or conventions that future agents should know.\n",
    "agent-resources/skills/ralph-loop/references/quality-gates.md": "# Ralph Quality Gates\n\nEvery completed story needs evidence.\n\n## Code stories\n\n- Typecheck passes.\n- Lint passes.\n- Unit or integration tests pass when relevant.\n\n## UI stories\n\n- Browser or manual visual verification is completed.\n- Loading, error, empty, disabled, and permission states are checked when applicable.\n\n## Data stories\n\n- DQ check SQL is provided.\n- Reconciliation check is provided.\n- Partition/watermark/backfill impact is documented.\n\n## Release stories\n\n- Rollback path exists.\n- Monitoring and runbook updates exist.\n",
    "agent-resources/skills/ralph-loop/evals/evals.json": "{\n  \"skill_name\": \"ralph-loop\",\n  \"evals\": [\n    {\n      \"id\": \"ralph-loop-001\",\n      \"prompt\": \"Review whether a PRD and prd.json are ready for a Ralph loop.\",\n      \"expected_output\": \"Readiness decision with blockers, story-size findings, quality gates, memory file checks, and next command.\"\n    }\n  ]\n}\n",
    ".product-dev/prompts/commands/prd-json.md": "# PRD JSON Command Prompt\n\nConvert PRD Markdown or feature design into Ralph-compatible `scripts/ralph/prd.json`.\n\n## Contract\n\nReturn a conversion summary and valid JSON with:\n\n- project\n- branchName: `ralph/<feature-name>`\n- description\n- userStories[] with id, title, description, acceptanceCriteria, priority, passes:false, notes:\"\"\n\n## Validation\n\nCheck JSON parseability, story size, dependency ordering, acceptance criteria quality, and quality evidence.\n",
    ".product-dev/prompts/commands/story-split.md": "# Story Split Command Prompt\n\nSplit PRD, feature design, or a broad request into Ralph-sized stories.\n\n## Rules\n\n- One story per fresh agent context.\n- Dependency order first, business value second.\n- Split too-large stories until each has a focused implementation boundary.\n- Each story has ID, title, type, description, acceptance criteria, dependency, and validation evidence.\n- Do not combine unrelated frontend, backend, data, and release work into one story.\n",
    ".product-dev/prompts/commands/ralph-readiness.md": "# Ralph Readiness Command Prompt\n\nReview whether the project is ready for Ralph-style loop execution.\n\n## Check\n\n- PRD completeness\n- prd.json schema and story size\n- dependency ordering\n- acceptance criteria verifiability\n- quality commands available\n- progress.txt append-only memory\n- AGENTS.md / CLAUDE.md reusable pattern guidance\n- branchName and git readiness\n- stop condition and COMPLETE behavior\n\nReturn a readiness decision: Approved, Approved with Conditions, or Not Ready.\n",
    "agent-resources/prompts/commands/architecture-diagram.md": "# Architecture Diagram Command Prompt\n\nGenerate evidence-backed Mermaid architecture diagrams: system context, container/component, deployment, sequence, data-flow, trust boundary, and observability/failure flow. Include purpose, source evidence, Mermaid code, interpretation notes, owner, and update trigger.\n",
    "agent-resources/prompts/commands/journey-diagram.md": "# Journey Diagram Command Prompt\n\nGenerate evidence-backed Mermaid user journey diagrams: journey map, user flow, state transition, funnel/friction, key interaction sequence, and instrumentation event flow.\n",
    "agent-resources/prompts/commands/diagram.md": "# Project Diagram Pack Prompt\n\nChoose and generate the smallest useful Mermaid diagram set for the current SDLC artifact. Do not invent unsupported systems or screens.\n",
    "agent-resources/skills/diagramming/SKILL.md": "---\nname: diagramming\ndescription: Generate and review Mermaid diagram-as-code for architecture, user journey, UI flow, API sequence, data lineage, ERD, pipeline DAG, DQ control, reconciliation, release, rollback, runbook, and incident workflows.\n---\n\n# Diagramming Skill\n\nUse Mermaid by default. Ground every node and edge in repo evidence, user input, PRD, DESIGN.md, SQL, or stated assumptions. Include purpose, source evidence, interpretation notes, owner, and update trigger.\n",
};

export async function initializePortableAgentResources(root: string): Promise<PortableResourceInitResult> {
  const createdDirectories: string[] = [];
  const createdFiles: string[] = [];

  for (const relativePath of PORTABLE_RESOURCE_DIRECTORIES) {
    await ensureDir(path.join(root, relativePath));
    createdDirectories.push(relativePath);
  }

  for (const [relativePath, content] of Object.entries(PORTABLE_RESOURCE_FILES)) {
    const absolute = path.join(root, relativePath);
    await ensureDir(path.dirname(absolute));
    if (!(await exists(absolute))) {
      await fs.writeFile(absolute, content, 'utf8');
      createdFiles.push(relativePath);
    }
  }

  return { createdDirectories, createdFiles };
}

export async function scanPortableAgentResources(root: string): Promise<string> {
  const paths = ['agent-resources', '.product-dev/prompts', '.product-dev/skills', '.opencode', '.github'];
  const lines: string[] = ['# Portable Agent Resource Scan', ''];
  for (const p of paths) {
    const abs = path.join(root, p);
    if (!(await exists(abs))) {
      lines.push(`- Missing: \`${p}\``);
      continue;
    }
    const files = await listFiles(abs, root);
    lines.push(`## ${p}`, '', files.length ? files.map(f => `- \`${f}\``).join('\n') : '- Empty', '');
  }
  lines.push('## Recommended Next Command', '', '`@product-dev /resources-init` if required resources are missing, otherwise `@product-dev /skill-scan` and `@product-dev /policy-scan`.');
  return lines.join('\n');
}

async function listFiles(dir: string, root: string): Promise<string[]> {
  const result: string[] = [];
  async function walk(current: string): Promise<void> {
    const entries = await fs.readdir(current, { withFileTypes: true }).catch(() => []);
    for (const entry of entries) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) await walk(full);
      else if (entry.isFile()) result.push(path.relative(root, full).replace(/\\/g, '/'));
    }
  }
  await walk(dir);
  return result.sort();
}
