/**
 * Product Dev Copilot Source Note
 *
 * File: src/writers/artifact-writer.ts
 * Purpose: Artifact writer. Writes generated markdown/YAML/SQL output into repository docs folders.
 *
 * Usage rules:
 * - Keep business-specific thresholds and local governance rules out of source code.
 * - Put company/department/country/project/environment rules in .product-dev/policy-packs/.
 * - Keep command outputs deterministic, reviewable, and written to repository artifacts whenever possible.
 * - For banking/data workflows, always preserve traceability, privacy, auditability, rollback, and human review.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import * as vscode from 'vscode';
import { RepoContext } from '../core/types';
import { ensureDir } from '../utils/fs-utils';

export async function writeArtifact(repo: RepoContext, relativePath: string, markdown: string): Promise<string | undefined> {
  if (!repo.config.writeArtifacts) return undefined;
  const outputPath = path.join(repo.workspaceRoot, repo.config.outputRoot, relativePath);
  await ensureDir(path.dirname(outputPath));
  await fs.writeFile(outputPath, normalizeMarkdown(markdown), 'utf8');
  return outputPath;
}

export async function openArtifact(filePath: string): Promise<void> {
  const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(filePath));
  await vscode.window.showTextDocument(doc, { preview: false });
}

function normalizeMarkdown(markdown: string): string {
  const header = `<!-- Generated by Company Product Dev Copilot. Review before using for delivery or approval. -->\n\n`;
  return `${header}${markdown.trim()}\n`;
}
