openapi: 3.0.3
info:
  title: Product API
  version: 1.0.0
paths: {}
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        traceId:
          type: string
